# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colSumSq_dge <- function(x, dim) {
    .Call(`_bravo_colSumSq_dge`, x, dim)
}

colSumSq_matrix <- function(x) {
    .Call(`_bravo_colSumSq_matrix`, x)
}

colMSD_dgc <- function(mat, m) {
    .Call(`_bravo_colMSD_dgc`, mat, m)
}

colSUMIDX_dgc <- function(mat) {
    .Call(`_bravo_colSUMIDX_dgc`, mat)
}

